name: publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build and publish
      id: build
      run: |
        python build.py
    - name: Zip
      run: |
        7z a SMCL_Windows_${{ github.ref }}.zip dist/smcl/*
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          SMCL_Windows_${{ github.ref }}.zip
        # tag_name: ${{ steps.build.outputs.version }}
        generate_release_notes: true