name: publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        python build.py
    - name: Run release script
      run: |
        python .github/release_util.py
    - name: Zip
      run: |
        7z a ${{ env.smcl_filename }} ./dist/smcl/* -p"smcl"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.smcl_filename }}
        tag_name: ${{ env.smcl_version }}
        generate_release_notes: true
        body_path: release_notes.md