name: publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        python build.py
    - name: Get Version
      run: |
        python .github/get_version.py >> "$GITHUB_ENV"
    - name: Zip
      run: |
        7z a ${{ env.smcl_version }}.zip ./dist/smcl/*
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.smcl_version }}.zip
        tag_name: ${{ env.smcl_version }}
        generate_release_notes: true